export function load() {
    return {
        questions: [
            "Wie heeft de grootste schoenen?🤡",
            "Wie is het meeste dramatisch",
            "Wie is grappiger",
            "Wie houd beter een geheim",
            "Wie is de betere danser",
            "Wie verliest rapper hun sleutels",
            "Wie heeft het meeste bang van spinnen/insecten",
            "Wie is het meest georganizeerd",
            "Wie is beter in dingen plannen",
            "Wie is altijd te laat",
            "Wie is spontaaner",
            "Wie is de betere datenight planner",
            "Wie zou het langste overleven op een alleen eiland",
            "Wie rijd het beste",
            "Wie is de mooiste",
            "Wie loopt het raps verloren",
            "Wie is liever buiten",
            "Wie zou een vliegtuig crash kunnen redden als piloot (met hulp van AC)",
            "Wie heeft de slechtste lach",
            "Wie kan het langste onder water ademen",
            "Wie kan de beste dieren geluiden maken (Demonstratie nodig!)",
            "Wie heeft de beste vrienden 👿",
            "Wie snurkt er het hardste",
            "Wie doet er het langste over om zich klaar te maken?",
            "Wie spendeert er meer geld?",
            "Wie liet er als eerste een scheetje in bijzijn van de ander? ",
            "Wie is de beste kok?",
            "Wie is het verantwoordelijkste in de relatie?",
            "Wie is de baas in de relatie?",
            "Wie had er als eerste een crush op de andere?",
            "Wie vergeet er het meeste?",
            "Wie verontschuldigd zich het eerste na een ruzie?",
            "Wie is er het koppigste?",
            "Wie spendeert er de meeste tijd aan computerspellen?",
            "Wie is er het schattigste?",
            "Wie is de grote lepel in bed?",
            "Wie is het meest romantisch?",
            "Wie heeft er altijd gelijk?",
            "Wie zei er als het eerste i love you?",
            "Wie kan er het beste geheimen houden?",
            "Wie heeft de beste zangstem in de douche?",
        ]
    }
}